version: '2'
services:
    td_portal-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/td_portal/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=td_portal
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
